### PR TITLE
Allow multiple CIs

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
tests are failed

**Comment by AndreyBelym** [comment]
FPR

**Comment by inikulin** [comment]
BTW can we have CI results in form of markdown list, instead of comma-separated values?

**Comment by AndreyBelym** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
